AllCops:
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/AsciiComments:
  Enabled: false
# inherit_gem:
#   rubocop-fjord:
#     - "config/rubocop.yml"
#     - "config/rails.yml"
